config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
  post 'sessions/create'
  delete 'sessions/destroy'

  root 'welcome#index'
  resources :time_logs
  resources :projects
  resources :developers

end

app/models/developer.rb
# Developer model
class Developer < ActiveRecord::Base
  has_many :time_logs, dependent: :restrict_with_error
  has_many :projects, through: :time_logs
  validates :email, uniqueness: true, presence: true
  has_secure_password

  def time_entered_in_current_week
    # TimeLog.where(developer_id: id)# will add date stuff
    time_logs.where(date: Date.today.all_week).map do |time_log|
      time_log.minutes
    end.sum
  end

  # before_destroy :cannot_delete_developers_with_time_entered
  #
  # def cannot_delete_developers_with_time_entered
  #   errors.add(:base, 'You cannot delete a developer who has entered time') if time_logs.any?
  #
  #   # If rails 5 replace `false` with `throw(:abort)`
  #   false if errors.present?
  # end

end

app/models/project.rb
# project model
class Project < ActiveRecord::Base
  has_many :time_logs, dependent: :restrict_with_error
  has_many :developers, through: :time_logs
  validates :name, uniqueness: true, presence: true
  validates_numericality_of :max_minutes, greater_than: 119, message: '| Projects must allow a minimum of two hours.'

  def sum_of_time_entered
    # TimeLog.where(project_id: id)
    time_logs.map do |time_log|
      time_log.minutes
    end.sum # => []

    # Extract values of a column, and then sum
    # time_logs.pluck(:minutes).sum

    # Have the DB sum values of a column (records must be saved)
    # time_logs.sum(:minutes)
  end

end

app/models/time_log.rb
# TimeLog Model
class TimeLog < ActiveRecord::Base
  belongs_to :developer
  belongs_to :project
  validates :project_id, presence: true
  validates_numericality_of :minutes, greater_than: 14, message: '| You must enter at least one increment of fifteen minutes.'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user

  # Memoized for performance only hit DB once
  def current_user
    @current_user ||= Developer.find_by(id: session[:developer_id])
  end

  helper_method :hours_and_minutes

  def hours_and_minutes(num_of_minutes)
    hours, minutes = num_of_minutes.divmod(60)
    "#{hours} hrs, #{minutes} mins"
  end



  # Check if a current_user is present otherwise redirect them.
  def check_for_authorized_user
    unless current_user
      redirect_to sessions_new_path
    end
  end

end

app/controllers/developers_controller.rb
# RuboCop wants a top-level class documentation comment here
class DevelopersController < ApplicationController
  before_action :check_for_authorized_user, except: [:new, :create]
  # use instance variable when you want data to flow to view
  def index
    @developers = Developer.all
  end

  # this method is an action
  def new
    @developer = Developer.new
  end

  def create
    @developer = Developer.new(developer_params)
    if @developer.save
      redirect_to developers_path
    else
      render :new
    end
  end

  def show
  end

  # this here is a querying method  .find yeah
  def edit
    @developer = Developer.find(params['id'])
  end

  def update
    @developer = Developer.find(params['id'])

    if @developer.update(developer_params)
      redirect_to developers_path
    else
      render :edit
    end
  end

  def destroy
    @developer = Developer.find(params['id'])
    if @developer.destroy
      redirect_to developers_path, notice: "Developer '#{@developer.name}' was destroyed!"
    else
      redirect_to developers_path, notice: @developer.errors.full_messages.join("\n")
    end
  end

  private def developer_params
    params.require('developer').permit(
      :name,
      :email,
      :password,
      :password_confirmation
    )
  end
end

app/controllers/projects_controller.rb
# RuboCop wants a top-level class documentation comment here
class ProjectsController < ApplicationController
  before_action :check_for_authorized_user
  def index
    @projects = Project.all
  end

  def new
    @project = Project.new
  end

  def create
    @project = Project.new(project_params)
    if @project.save
      redirect_to projects_path
    else
      render :new
    end
  end

  def edit
    @project = Project.find(params['id'])
  end

  def update
    @project = Project.find(params['id'])

    if @project.update(project_params)
      redirect_to projects_path
    else
      render :edit
    end
  end

  def destroy
    @project = Project.find(params['id'])
    if @project.destroy
      redirect_to projects_path, notice: "Project '#{@project.name}' successfully deleted!"
    else
      redirect_to projects_path, notice:
      @project.errors.full_messages.join("\n")
    end
  end

  private def project_params
    params.require('project').permit(
      :name,
      :max_minutes
    )
  end
end

app/controllers/sessions_controller.rb
# RuboCop wants a top-level class documentation comment here
class SessionsController < ApplicationController
  # show form
  def new
  end

  # do work when they submit form
  def create
    # @developer = search database for email that was typed in
    @developer = Developer.find_by(email: params[:email])
    # if they log in right:
    if @developer && @developer.authenticate(params[:password])
      # need to be remembered as logged in on all pages
      session[:developer_id] = @developer.id
      session[:developer_welcome] = @developer.name
      # session[:its_a_party_key] = "You logged in dude"
      # they get a welcome page REDIRECT
      redirect_to root_path, notice: "Welcome back, #{@developer.name}!"
    else
      flash[:notice] = 'Password or username wrong. Try again.'
      render :new
    end
  end

  # end session by resetting developer id to nil
  def destroy
    session[:developer_id] = nil
    redirect_to sessions_new_path
  end
end

app/controllers/time_logs_controller.rb
# RuboCop wants a top-level class documentation comment here
class TimeLogsController < ApplicationController
  before_action :check_for_authorized_user
  rescue_from ActiveRecord::RecordNotFound, with: :unauthorized

  def index
    # @time_logs = TimeLog.where(developer_id: current_user.id)
    @time_logs = current_user.time_logs
  end

  def new
    @time_log = TimeLog.new
  end

  def create
    @time_log = current_user.time_logs.build(time_log_params)
    if @time_log.save
      redirect_to time_logs_path
    else
      render :new
    end
  end

  def edit
    @time_log = current_user.time_logs.find(params['id'])
  end

  def update
    @time_log = current_user.time_logs.find(params['id'])

    if @time_log.update(time_log_params)
      redirect_to time_logs_path
    else
      render :edit
    end
  end

  def destroy
    @time_log = current_user.time_logs.find(params['id'])
    @time_log.destroy
    redirect_to time_logs_path
  end

  private def time_log_params
    params.require('time_log').permit(
      :date,
      :minutes,
      :project_id
    )
  end

  private def unauthorized
    redirect_to time_logs_path, notice: 'You do not have access to this page.'
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/developers_helper.rb
module DevelopersHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/time_logs_helper.rb
module TimeLogsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/developers/edit.html.erb
<h2>
  Edit a Developer
</h2>

<%= form_for @developer, url: developer_path(id: @developer.id), method: :patch do |f| %>
<p>
  <%= f.label :name %>
  <%= f.text_field :name %>
</p>
<p>
  <%= f.label :email %>
  <%= f.text_field :email %>
</p>
<p>
  <%= f.submit "Save" %>
  <%= f.submit "Cancel" %>
</p>
<% end %>

app/views/developers/index.html.erb
<table class="table">
  <h2>Employee Directory</h2>
  <th>Name</th>
  <th>Email</th>
  <th></th>
  <th></th>
  <tbody>
    <% @developers.each do |developer| %>
    <%= content_tag_for :tr, developer do %>
    <% if developer.time_entered_in_current_week > 2400 %>
    <tr class="text-danger">
      <% else %>
      <tr>
        <% end %>
        <td>
          <%= developer.name %>
        </td>
        <td>
          <%= developer.email %>
        </td>
        <td>
          <%= link_to "Edit", edit_developer_path(developer.id) %>  |
          <%= link_to "Delete", developer_path(developer.id), method: :delete %>
        </td>
      </tr>
      <% end %>
      <% end %>
    </tbody>
  </table>

app/views/developers/new.html.erb
<h2>
  New developer
</h2>

<%= form_for @developer, url: developers_path do |f| %>
<p>
  <%= f.label :name %>
  <%= f.text_field :name %>
</p>
<p>
  <%= f.label :email %>
  <%= f.text_field :email %>
</p>
<p>
  <%= f.label :password %>
  <%= f.password_field :password %>
</p>
<p>
  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation %>
</p>
<p>
  <%= f.submit "Save" %>
</p>
<% end %>

<% if @developer.errors.any? %>
<ul>
  <% for message_error in @developer.errors.full_messages %>
  <li>
    <%= message_error %>
  </li>
  <% end %>
</ul>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <link rel="stylesheet" href="/css/bootstrap.min.css" media="screen" type="text/css">
  <link rel="stylesheet" href="/css/styles.css" media="screen" title="no title">
  <title>TimeTracker</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link rel="shortcut icon" type="image/x-icon" href="/favicon.ico">
</head>
<body>

  <div class="navbar navbar-default navbar-static-top">
    <div class="container">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">Time Tracker</a>
      <div class="navbar-collapse collapse navbar-responsive-collapse">
        <ul class="nav navbar-nav navbar-right">
          <% if current_user %>
          <li><%= link_to "Time Entries", time_logs_path, method: :get %></li>
          <li><%= link_to "Projects", projects_path, method: :get %></li>
          <li><%= link_to "Developers", developers_path, method: :get %></li>
          <p class="navbar-text">
            <%= current_user.name %>  |
            <%= link_to "Log out", sessions_destroy_path, method: :delete %>
          </p>
          <% else %>
          <p class="navbar-text">
            <%= link_to "Register", new_developer_path %>  |  
            <%= link_to "Sign in", sessions_new_path %>
          </p>
          <% end %>

        </ul>
      </div>
    </div>
  </div>
  <div class="container">
    <div class="col-lg-9">

      <%= notice %>

      <%= yield %>

    </div>

    <div class="col-lg-3">
      <div class="well sidebar-nav">
        <h3>Make a new</h3>
        <ul class="nav nav-list">
          <li>
            <%= button_to "Project", new_project_path, method: :get, class: "btn btn-secondary"  %>
          </li><br>
          <li>
            <%= button_to "Developer", new_developer_path, method: :get, class: "btn btn-secondary"  %>
          </li><br>
          <li>
            <%= button_to "Time Entry", new_time_log_path, method: :get, class: "btn btn-secondary"  %>
          </li><br>
        </ul>
      </div>
    </div>
  </div>
</body>
</html>

app/views/projects/edit.html.erb
<h2>
  Edit a project
</h2>

<%= form_for @project, url: project_path(id: @project.id), method: :patch do |f| %>
<p>
  <%= f.label :name %>
  <%= f.text_field :name %>
</p>
<p>
  <%= f.label :max_minutes %>
  <%= f.number_field :max_minutes, step: 15, min: 120 %>
</p>
<p>
  <%= f.submit "Save" %>
  <%= f.submit "Cancel" %>
</p>
<% end %>

<% if @project.errors.any? %>
<ul>
  <% for message_error in @project.errors.full_messages %>
  <li>
    <%= message_error %>
  </li>
  <% end %>
</ul>
<% end %>

app/views/projects/index.html.erb
<table class="table">
  <h2>Projects</h2>
  <th>Name</th>
  <th>Allowed Time</th>
  <th>Time Entered</th>
  <th></th>
  <tbody>
    <% @projects.each do |project| %>
    <%= content_tag_for :tr, project do %>
    <% if project.max_minutes < project.sum_of_time_entered %>
    <tr class="text-danger">
      <% else %>
      <tr>
        <% end %>
        <td>
          <%= project.name %>
        </td>
        <td>
          <%= hours_and_minutes(project.max_minutes) %>
        </td>
        <td>
          <%= hours_and_minutes(project.sum_of_time_entered) %>
        </td>
        <td>
          <%= link_to "Edit", edit_project_path(project.id) %>  |
          <%= link_to "Delete", project_path(project.id), method: :delete %>
        </td>
      </tr>
      <% end %>
      <% end %>
    </tbody>
  </table>

app/views/projects/new.html.erb
<h2>
  New project
</h2>

<%= form_for @project, url: projects_path do |f| %>
<p>
  <%= f.label :name %>
  <%= f.text_field :name %>
</p>
<p>
  <%= f.label :max_minutes %>
  <%= f.number_field :max_minutes, step: 15, min: 120 %>
</p>
<p>
  <%= f.submit "Save" %>
  <%= f.submit "Cancel" %>
</p>
<% end %>

<% if @project.errors.any? %>
<ul>
  <% for message_error in @project.errors.full_messages %>
  <li>
    <%= message_error %>
  </li>
  <% end %>
</ul>
<% end %>

app/views/time_logs/edit.html.erb
<h2>
  Edit a time entry
</h2>

<%= form_for @time_log, url: time_log_path(id: @time_log.id), method: :patch do |f| %>
<p>
  <%= f.label :date %>
  <%= f.date_field :date, value: Time.now.to_date %>
</p>
<p>
  <%= f.label :project_id, :Project %>
  <%= f.select :project_id, Project.all.collect { |p| [p.name, p.id] }, include_blank: true %>
</p>
<p>
  <%= f.label :minutes %>
  <%= f.number_field :minutes, step: 15, in: 0..1440 %>
</p>
<p>
  <%= f.submit "Save" %>
</p>
<% end %>

<% if @time_log.errors.any? %>
<ul>
  <% for message_error in @time_log.errors.full_messages %>
  <li>
    <%= message_error %>
  </li>
  <% end %>
</ul>
<% end %>

app/views/time_logs/index.html.erb
<table class="table">
  <h2>My time logs</h2>
  <th>Date</th>
  <th>Project</th>
  <th>Time Entered</th>
  <th></th>
  <tbody>
    <% @time_logs.each do |time_log| %>
    <%= content_tag_for :tr, time_log do %>
    <td>
      <%= time_log.date %>
    </td>
    <td>
      <!-- <%#= time_log.project.name if time_log.project %>  #synonymous with: -->
      <!-- <%#= time_log.project&.name %>                     #synonymous with: -->
      <%= time_log.project.try(:name) %>
    </td>
    <td>
      <%= hours_and_minutes(time_log.minutes) %>
    </td>
    <td>
      <%= link_to "Edit", edit_time_log_path(time_log.id) %>  |
      <%= link_to "Delete", time_log_path(time_log.id), method: :delete %>
    </td>
    <% end %>
    <% end %>
  </tbody>
</table>

app/views/time_logs/new.html.erb
<h2>
  New time entry
</h2>

<%= form_for @time_log, url: time_logs_path do |f| %>
<p>
  <%= f.label :date %>
  <%= f.date_field :date, value: Time.now.to_date %>
</p>
<p>
  <%= f.label :project_id, :Project %>
  <%= f.select :project_id, Project.all.collect { |p| [p.name, p.id] }, include_blank: true %>
</p>
<p>
  <%= f.label :minutes %>
  <%= f.number_field :minutes, step: 15, in: 0..1440 %>
</p>
<p>
  <%= f.submit "Save" %>
</p>
<% end %>

<% if @time_log.errors.any? %>
<ul>
  <% for message_error in @time_log.errors.full_messages %>
  <li>
    <%= message_error %>
  </li>
  <% end %>
</ul>
<% end %>

app/views/welcome/index.html.erb
<h1>
  Welcome to Time Tracker
</h1>

<h3>
  <i>
    The most advanced website on the internet.
  </i>
</h3>


<!-- <p>
<%#= session[:developer_welcome] %>
</p> -->



<%# session[:its_a_party_key] %>